minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - '@tktb-tess/*'
  - next
  - '@next/*'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@tktb-tess/my-zod-schema'
  - sharp
  - unrs-resolver
